### ISSUE TITLE
Missing requirements.txt

### ISSUE THREAD

**Issue by scivision** [ec500-software-engineering/exercise-1-modularity-qzhizhou#1]
We can't build this without requirements.txt since it uses libraries not built-in to Python

**Comment by qzhizhou** [comment]
I've added the requirement file, please let me know if you have any questions.

**Comment by qzhizhou** [comment]
> We can't build this without requirements.txt since it uses libraries not built-in to Python
I've added the requirement file, please let me know if you have any questions.
